---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-integration
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: service-integration
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: service-integration
    spec:
      containers:
      - name: service-integration
        image: ghcr.io/drolx/trace-service-integration:0.0.1-preview.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: service-integration-env
        - secretRef:
            name: service-integration-secrets
      terminationGracePeriodSeconds: 180
